# Generated by Django 4.0 on 2021-12-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_pruduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pruduct',
            new_name='Product',
        ),
    ]
